use_frameworks!

platform :ios, '11.0'

target 'dojo-ios-sdk_Example' do
  pod 'dojo-ios-sdk', :path => '../', :testspecs => ['dojo-ios-sdk-tests']
  pod 'CocoaDebug', :configurations => ['Debug'] #network trafic tool

  target 'dojo-ios-sdk_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end
